import numpy as np
import matplotlib.pyplot as plt

# sin(x)
x1 = np.linspace(0, 50, 500)
plt.figure()
plt.plot(x1, np.sin(x1), label="sin(x)")
plt.title("sin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

# cos(x)
plt.figure()
plt.plot(x1, np.cos(x1), label="cos(x)")
plt.title("cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

# tan(x)
plt.figure()
plt.plot(x1, np.tan(x1), label="tan(x)")
plt.title("tan(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.ylim(-10, 10)  # Limit y-axis for tan(x)
plt.show()

# asin(x)
x2 = np.linspace(-1, 1, 100)
plt.figure()
plt.plot(x2, np.arcsin(x2), label="arcsin(x)")
plt.title("arcsin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

# acos(x)
plt.figure()
plt.plot(x2, np.arccos(x2), label="arccos(x)")
plt.title("arccos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

# atan(x)
x3 = np.linspace(-10, 10, 200)
plt.figure()
plt.plot(x3, np.arctan(x3), label="arctan(x)")
plt.title("arctan(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)